name: mtg
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astroid=2.9.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - autopep8=1.6.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - bleach=5.0.1
  - bzip2=1.0.8
  - ca-certificates=2022.4.26
  - certifi=2022.6.15
  - cffi=1.15.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - flit-core=3.7.1
  - importlib-metadata=4.11.4
  - importlib_resources=5.8.0
  - ipykernel=6.9.1
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.1
  - isort=5.9.3
  - jedi=0.18.1
  - jinja2=3.1.2
  - jsonschema=4.7.2
  - jupyter_client=7.2.2
  - jupyter_core=4.10.0
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=1.1.1
  - lazy-object-proxy=1.6.0
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.0.3
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.2
  - mccabe=0.7.0
  - mistune=0.8.4
  - nbclient=0.5.13
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - notebook=6.4.12
  - openssl=1.1.1q
  - packaging=21.3
  - pandoc=2.18
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.1.2
  - platformdirs=2.4.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pygments=2.11.2
  - pylint=2.12.2
  - pyparsing=3.0.9
  - pyrsistent=0.18.1
  - python=3.10.4
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.1
  - python_abi=3.10
  - pyzmq=23.2.0
  - readline=8.1.2
  - send2trash=1.8.0
  - setuptools=61.2.0
  - six=1.16.0
  - soupsieve=2.3.1
  - sqlite=3.38.5
  - stack_data=0.2.0
  - terminado=0.15.0
  - tinycss2=1.1.1
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.1
  - traitlets=5.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.6.1
  - wrapt=1.13.3
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.12
  - pip:
    - absl-py==1.1.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - aitextgen==0.5.2
    - async-timeout==4.0.2
    - cachetools==5.2.0
    - charset-normalizer==2.1.0
    - filelock==3.7.1
    - fire==0.4.0
    - frozenlist==1.3.0
    - fsspec==2022.5.0
    - google-auth==2.9.1
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - huggingface-hub==0.8.1
    - idna==3.3
    - lxml==4.9.1
    - markdown==3.4.1
    - multidict==6.0.2
    - numpy==1.23.1
    - oauthlib==3.2.0
    - pandas==1.4.3
    - pillow==9.2.0
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.2
    - pytorch-lightning==1.6.5
    - pytz==2022.1
    - pyyaml==6.0
    - regex==2022.7.9
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - tokenizers==0.12.1
    - torch==1.12.0
    - torchmetrics==0.9.2
    - tqdm==4.64.0
    - transformers==4.20.1
    - typing-extensions==4.3.0
    - urllib3==1.26.10
    - werkzeug==2.1.2
    - yarl==1.7.2
